apiVersion: v1
kind: Service
metadata:
  name: flask-change-service
spec:
  selector:
    app: change-python
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: change-python
spec:
  selector:
    matchLabels:
      app: change-python
  replicas: 3
  template:
    metadata:
      labels:
        app: change-python
    spec:
      containers:
      - name: flask-change
        image: flask-change:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000